[build]
    command = "npm run build"
    publish = "dist"

[build.environment]
    NITRO_PRESET = "netlify"

[[redirects]]
    from = "https://blog.nocp.space/*"
    to = "https://nocp.space/blog"
    status = 301
    force = true

[[redirects]]
    from = "https://nocpiun.net/*"
    to = "https://nocp.space"
    status = 301
    force = true

[[redirects]]
    from = "https://blog.nocpiun.net/*"
    to = "https://nocp.space/blog"
    status = 301
    force = true
